services:
  vite_docker:
    image: node:alpine
    container_name: vitedocker
    entrypoint: /bin/sh
    ports:
      - 5175:5175
    working_dir: /srv/app
    volumes:
      - nodemodules:/srv/app/node_modules
      - type: bind
        source: ./
        target: /srv/app
    tty: true

volumes:
  nodemodules: {}